// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"
// To parse this JSON data, do
//
//     final quiz = quizFromJson(jsonString);
//     final selection = selectionFromJson(jsonString);
//     final answer = answerFromJson(jsonString);

import 'dart:convert';

Quiz quizFromJson(String str) {
    final jsonData = json.decode(str);
    return Quiz.fromJson(jsonData);
}

String quizToJson(Quiz data) {
    final dyn = data.toJson();
    return json.encode(dyn);
}

Selection selectionFromJson(String str) {
    final jsonData = json.decode(str);
    return Selection.fromJson(jsonData);
}

String selectionToJson(Selection data) {
    final dyn = data.toJson();
    return json.encode(dyn);
}

Answer answerFromJson(String str) {
    final jsonData = json.decode(str);
    return Answer.fromJson(jsonData);
}

String answerToJson(Answer data) {
    final dyn = data.toJson();
    return json.encode(dyn);
}

class Quiz {
    List<Answer> answer;
    String description;
    String name;
    List<Selection> selections;

    Quiz({
        this.answer,
        this.description,
        this.name,
        this.selections,
    });

    factory Quiz.fromJson(Map<String, dynamic> json) => new Quiz(
        answer: new List<Answer>.from(json["answer"].map((x) => Answer.fromJson(x))),
        description: json["description"],
        name: json["name"],
        selections: new List<Selection>.from(json["selections"].map((x) => Selection.fromJson(x))),
    );

    Map<String, dynamic> toJson() => {
        "answer": new List<dynamic>.from(answer.map((x) => x.toJson())),
        "description": description,
        "name": name,
        "selections": new List<dynamic>.from(selections.map((x) => x.toJson())),
    };
}

class Answer {
    String description;
    double index;

    Answer({
        this.description,
        this.index,
    });

    factory Answer.fromJson(Map<String, dynamic> json) => new Answer(
        description: json["description"],
        index: json["index"].toDouble(),
    );

    Map<String, dynamic> toJson() => {
        "description": description,
        "index": index,
    };
}

class Selection {
    String description;

    Selection({
        this.description,
    });

    factory Selection.fromJson(Map<String, dynamic> json) => new Selection(
        description: json["description"],
    );

    Map<String, dynamic> toJson() => {
        "description": description,
    };
}
